// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiS8XQLWgV6jkqWy5JJVpwsYcKYaFtAn4',
    appId: '1:978406565554:android:f8ff0e1fa4843f4ea54bab',
    messagingSenderId: '978406565554',
    projectId: 'tradingapp-525d6',
    storageBucket: 'tradingapp-525d6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHjZxsiHfeikzhGJ2i90YL1JzpnVivzGs',
    appId: '1:978406565554:ios:cfd1c671a145f458a54bab',
    messagingSenderId: '978406565554',
    projectId: 'tradingapp-525d6',
    storageBucket: 'tradingapp-525d6.firebasestorage.app',
    iosBundleId: 'com.example.tradingapps',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcILlwJ3sPzfsm6entCCHgRd7SW8fKq4I',
    appId: '1:978406565554:web:db6f4cd85ed5d2eca54bab',
    messagingSenderId: '978406565554',
    projectId: 'tradingapp-525d6',
    authDomain: 'tradingapp-525d6.firebaseapp.com',
    storageBucket: 'tradingapp-525d6.firebasestorage.app',
    measurementId: 'G-JYG4FMTTVE',
  );
}